"""Project current C11 decisions and the inherited-coverage report."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from .coverage import coverage_report
from .extract import extract_questions


_C11_HEADING = re.compile(r"^### Q(\d+)\b\s*(.*)$")
_C11_SECTION_END = re.compile(r"^(?:### Q\d+\b|## Round\b|---$)")
_CAMPAIGNS = [f"C{index}" for index in range(1, 11)]


def _c11_path(root: Path) -> Path:
    for candidate in (root / "docs" / "GRILLING-C11.md", root / "GRILLING-C11.md"):
        if candidate.exists():
            return candidate
    raise FileNotFoundError("no C11 record found")


def extract_current_decisions(root: Path) -> list[dict]:
    path = _c11_path(root)
    raw = path.read_bytes()
    lines = raw.decode("utf-8").splitlines()
    digest = hashlib.sha256(raw).hexdigest()
    rows: list[dict] = []
    for index, line in enumerate(lines):
        match = _C11_HEADING.match(line)
        if not match:
            continue
        number = int(match.group(1))
        section: list[str] = []
        for following in lines[index + 1 :]:
            if _C11_SECTION_END.match(following):
                break
            section.append(following)
        answer = next(
            (item.strip() for item in section if item.strip().startswith("✔")),
            "",
        )
        rows.append(
            {
                "id": f"C11-Q{number}",
                "aliases": [f"Q{number}"],
                "source_file": path.name,
                "source_line": index + 1,
                "source_digest": digest,
                "question_text": match.group(2).strip(),
                "answer_summary": answer,
                "review_state": "reviewed",
                "disposition": None,
                "capability_id": None,
                "target_stage": None,
            }
        )
    return rows


def _write_json(path: Path, value: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def _render_decisions(rows: list[dict]) -> str:
    lines = [
        "# Decision ledger projection",
        "",
        "Generated from `docs/design/decisions.json`; do not edit this file.",
        "",
        "| ID | Aliases | State | Source | Question |",
        "|---|---|---|---|---|",
    ]
    for row in sorted(rows, key=lambda item: item["id"]):
        question = row.get("question_text", "").replace("|", "\\|").replace("\n", " ")
        aliases = ", ".join(row.get("aliases", []))
        source = f"{row.get('source_file', '')}:{row.get('source_line', '')}"
        lines.append(
            f"| `{row['id']}` | {aliases} | {row.get('review_state', '')} | `{source}` | {question} |"
        )
    return "\n".join(lines) + "\n"


def project_package(root: Path) -> int:
    package = root / "docs" / "design"
    decisions_path = package / "decisions.json"
    current = extract_current_decisions(root)
    if decisions_path.exists():
        existing = json.loads(decisions_path.read_text(encoding="utf-8"))
    else:
        existing = {"schema_version": 1, "design_revision": 1, "decisions": []}
    by_id = {row["id"]: row for row in existing.get("decisions", [])}
    by_id.update({row["id"]: row for row in current})
    decisions = [by_id[key] for key in sorted(by_id)]
    existing["decisions"] = decisions
    existing.setdefault("schema_version", 1)
    existing.setdefault("design_revision", 1)
    existing["generator"] = "tools/design/project.py"
    _write_json(decisions_path, existing)

    inherited = extract_questions(root, _CAMPAIGNS, report_unparsed=True)
    coverage = coverage_report(inherited.records, {"decisions": decisions})
    coverage.update(
        {
            "schema_version": 1,
            "kind": "inherited-coverage-draft",
            "canonical": False,
            "generator": "tools/design/project.py",
            "source_digest_by_file": {
                record["source_file"]: record["source_digest"]
                for record in inherited.records
            },
            "unparsed": inherited.unparsed,
            "reused_aliases": inherited.reused_aliases,
            "missing_ranges": inherited.missing_ranges,
        }
    )
    _write_json(package / "generated" / "coverage.draft.json", coverage)
    projection = package / "generated" / "decisions.md"
    projection.parent.mkdir(parents=True, exist_ok=True)
    projection.write_text(_render_decisions(decisions), encoding="utf-8")
    return 0
